### ISSUE TITLE
ganalytics affecting PayPal currency during checkbox

### ISSUE THREAD

**Issue by heskethm** [PrestaShop/ganalytics#66]
Hi guys,

When checking out an order with a different currency currency, the currency gets changed to the default but the amount is unchanged. For example, an order of $15.41 should convert to £9.99 in PayPal, but instead converts to £15.41.

I know this seems completely unrelated, but I have found this issue only goes away and reoccurs when enabling / disabling ganalytics 2.x.

I believe this has something to do with the PayPal module updating the customers cart before payment, which in turn triggers a hook Google Analytics uses, overwriting the currency change. I'm not sure though, I have not been able to pinpoint the issue.

I replied to a post about this in April, and there are others who are having the same issue:
https://www.prestashop.com/forums/topic/402148-paypal-europe-issue-with-currency-after-update-from-1609-to-11/?p=2033247

Is this a known issue that can be resolved?

**Comment by Quetzacoalt91** [comment]
Hi @heskethm,

This issue has also been reported on January on the PrestaShop forge and should be fixed with Google Analytics 2.2.0.
Does the issue still occurs with the module updated ? Please note that the version 2.3.0 will be published tomorrow.

For more information:
* http://forge.prestashop.com/browse/PNM-3435
* Commit https://github.com/PrestaShop/ganalytics/commit/44f72fce0556f4761ba6656a7ba6dabd12b6388d

Best regards

**Comment by heskethm** [comment]
Hey @Quetzacoalt91 

That's great, sorry I hadn't seen the Forge report, but I'm very grateful you were able to look into this and apply a fix.

Many thanks,
Mark
