### ISSUE TITLE
Transaction send with Ganalytics module disabled

### ISSUE THREAD

**Issue by okom3pom** [PrestaShop/ganalytics#75]
Hi,

When the module is disabled it still sends the transactions.

See /classes/Hook.php  getHookModuleExecList

Okom3pom

**Comment by Quetzacoalt91** [comment]
Yeah that's right. I guess this with the hook `BackOfficeHeader`, which is always called even if the module is disabled.
This is caused by the possible configuration of the module, even disabled. This hook is supposed to load all CSS and JS files needed to display the page properly.

I have just modified the module regarding this issue: https://github.com/PrestaShop/ganalytics/commit/c3e2578a39830c918e342f89ff99320736ea4ed9

Best regards

cc @cedricfontaine

**Comment by okom3pom** [comment]
Thanks !

Okom3pom
